config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'students/index'
  get 'students/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  get '/:locale' => 'homepage#index'

  scope "(:locale)", locale: /fr|en|nl|ar/ do
    root "homepage#index"
    get 'about' => "homepage#about"
    get 'history' => "homepage#history"
    get 'francois_house' => "homepage#francois_house"
    get 'perspectives' => "homepage#perspectives"
    get 'private_life' => "homepage#private_life"
    get 'press' => "homepage#press"
    get 'contact' => "homepage#contact"
    get 'support' => "homepage#support"
    get 'partenaire' => "homepage#partenaire"
    get 'testimony' => "homepage#testimony"
    resources :homepage , only: [:index, :about, :history, :house, :perspectives, :testimony]
    resources :projects
    resources :students
    resources :volunteers
  end
end
  

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  has_many :students, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :subsections
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :project
end

app/models/subsection.rb
class Subsection < ApplicationRecord
  belongs_to :section
end

app/models/trainee.rb
class Trainee < ApplicationRecord
  belongs_to :project

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  around_action :switch_locale

  def default_url_options(options={})
    { :locale => I18n.locale == I18n.default_locale ? nil : I18n.locale  }
  end

  def default_url_options
    { locale: I18n.locale }
  end
  
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index 
  end

  def about
  end

  def private_life
  end 

  def press 
  end

  def history
  end

  def francois_house
  end 

  def perspectives
  end

  def partenaire
  end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end 

  def new
    @project = Project.new
  end 

  def create

  end 
  
  def join_project
    @project = Project.new(project_params)
    @project.trainees.build

    if(@project.save)
        
    else
      render :new
    end 
  end 
  

  private 

  def project_params
    params.require(:projects).permit(:id, :title, :description, :trainees_attributes[:id, :name, :lastname, :telephone, :email])
  end 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create!(student_params) 
    if @student.valid?
        redirect_to student_path(@student)
    else
      render :new
    end 
  end

  def show 
    @student= Student.find(params[:id])
  end 


  private 

  def student_params
    params.require(:student).permit(:name, :lastname, :telephone, :email, :project_id)
  end
end

app/controllers/trainees_controller.rb
class TraineesController < ApplicationController

  def new
    @trainee = Trainee.new
  end

  def create  
    @trainee = Trainee.new(trainee_params)
    if @trainee.valid?
      @trainee.save
      redirect_to trainee_path(@trainee)
    else
      render :new
    end
  end 

  def show
  end

  private 

  def trainee_params
    params.require(:trainee).permit(:name, :lastname, :telephone, :email, :project_attributes[:title])
  end 
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def new
    
  end

  def create
  end

  private 

  def vonlunteer_params
    params.require(:volunteers).permit(:id, :section_id, :subsection_id)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/trainees_helper.rb
module TraineesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/homepage/about.html.erb
<div class="container-fluid container-about-seeme">
  <h2 class="title text-center"><%= t('about.title') %></h2>
  <div class="row">
    <div class="col-12">
      <%= image_tag('Imane_seeme-about-us.jpg', class: "img-fluid img-intro", alt: "Imane Maison François, photo: P-Y. Thienpont. Le Soir ") %>
    </div>
  </div>
  <div class="lines">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
  <div class="row sub-content">
    <div class="col-md-6">
      <div class="inner_sub-content">
        <h3><%= t('about.presentation.title') %></h3>
        <p><%= t('about.presentation.paragraph_one_html') %></p>
        <p><%= t('about.presentation.paragraph_two_html') %></p>
        <p><%= t('about.presentation.paragraph_three_html') %></p>
        <p><%= t('about.presentation.paragraph_four_html') %></p>
        <h3><%= t('about.story.title') %></h3>
        <p><%= t('about.story.paragraph_one_html') %></p>
        <button class="text-center button_seeme"><%= link_to t('about.story.article'), "https://plus.lesoir.be/131564/article/2017-12-29/imane-cest-extraordinaire-de-pouvoir-offrir-un-bout-de-vie-normale", target: "_blank"  %></button>
        <%= image_tag("about_us_historic.jpg", class: "img-fluid img-historic", alt: "Famille accueillie à la maison François") %>
      </div>
    </div>
  </div>
</div>

app/views/homepage/contact.html.erb
<div class="container container-contact">
  <div class="hero-title">
    <div class="col-8">
      <h2><%=  t('contact.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag "" %>
    </div>
  </div>
  <div class="content">
    <div class="contact_group">
      <span><i class="fa fa-user"></i>Imane El Kart </span>
      <span><a href="tel:+32494675067"><i class="fa fa-tty"></i>+32 494 67 50 67</a></span>
      <span><a href="mailto:i.elkart@seeme-refugees.com"><i class="fas fa-at"></i>i.elkart@seeme-refugees.com</a></span>
      <span><i class="fa fa-map-marker-alt"></i>Avenue du roi Soldat 118 </span>
      <span><i class="fa fa-map-marker-alt"></i>1070 Bruxelles</span>
    </div>
    <p class="description"><%= t('contact.description') %></p>
  </div>
</div>

app/views/homepage/francois_house.html.erb
<div class="container-fluid container-about-seeme">
  <div class="row sub-content">
    <div class="col-md-12">
      <div class="row">
        <div class="col-12"><h3 class="text-center"><%= t('about.story.maison_francois') %></h3></div>
        <div class="col-12"><h4><%= t('about.story.maison_francois_subtitle_html') %></h4></div>
      </div>
      <div class="row">
        <div class="col-6">
          <p><%= t('about.story.paragraph_two_html') %></p>
        </div>
        <div class="col-6">
          <p><%= t('about.story.paragraph_three_html') %></p>
        </div>
      </div>
    </div>
    <div class="col align-self-center">
      <div class="container_img">
          <%= image_tag("Imane_seeme-about-us.jpg", class: "fit-left", alt: "") %>
          <%= image_tag("Imane_seeme-about-us.jpg", class: "portrait", alt: "") %>
          <%= image_tag("Imane_seeme-about-us.jpg", class: "fit-right", alt: "") %>
          <%= image_tag("Imane_seeme-about-us.jpg", class: "", alt: "") %>
          <%= image_tag("Imane_seeme-about-us.jpg", class: "fit-left portrait", alt: "") %>
          <%= image_tag("Imane_seeme-about-us.jpg", class: "", alt: "") %>
        </div>
    </div>
    <div class="row chiffres">
      <div class="col-12"><h4><%= t('about.story.chiffres') %></h4></div>
      <div class="col-6 col-md-3">
        <div class="ico">
          <%= image_tag("teamwork.jpg", class: "img-one", alt: "") %>
        </div>
        <span><%= t('about.story.icon_one') %></span>
      </div>
      <div class="col-6 col-md-3">
        <div class="ico">
          <%= image_tag("night.jpg", class: "img-two", alt: "") %>
        </div>
        <span><%= t('about.story.icon_two') %></span>
      </div>
      <div class="col-6 col-md-3">
        <div class="ico">
          <%= image_tag("meal.jpg", class: "img-three", alt: "") %>
        </div>
        <span><%= t('about.story.icon_three') %></span>
      </div>
      <div class="col-6 col-md-3">
        <div class="ico">
          <%= image_tag("execution.jpg", class: "img-four", alt: "") %>
        </div>
        <span><%= t('about.story.icon_four') %></span>
      </div>
    </div>
    <div class="lines">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</div>

app/views/homepage/history.html.erb
<div class="container-fluid container-about-seeme">
  <div class="row">
    <div class="col-12">
      <h3><%= t('about.story.title_thanks') %></h3>
    </div>
    <div class="col-6 col-md-4">
      <%= t('about.story.para_one') %>
    </div>
    <div class="col-6 col-md-4">
      <%= t('about.story.para_two') %>
    </div>
    <div class="col-6 col-md-4">
      <%= t('about.story.para_three') %>
    </div>
  </div>
  <div class="col-12">
    <h3><%= t('about.story.title_adventure_continue') %></h3>
  </div>
</div>

app/views/homepage/index.html.erb
<div class="container_index">
  <div class="img_hp">
    <%= image_tag "image_hp.jpg" %>
    <div class="lines">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
  <div class="row text_hp">
    <div class="col-md-4 text_hp__logo">
      <%= image_tag "logo_SeeMe.png" %>
    </div>
    <div class="col-md-8 text_hp__intro">
      <div class="text_hp__title">
        <h3><span><%= t('index.before_title') %></span><%= t('index.title') %></h3>
      </div>
      <p><%= t('index.intro') %></p>
    </div>
  </div>
</div>

app/views/homepage/partenaire.html.erb
<div class="container container-support">
  <div class="hero-title">
    <div class="col-8">
      <h2><%=  t('partner.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag "support.png" %>
    </div>
  </div>
  <div class="content">
     <p class="description"><%= t('partner.description') %></p>
     <div class="help_content">
        
        <div class="bloc_section">
          <section class="section__content section__content1">
            <div class="description">
              <p><%= t('partner.content.one_html') %></p>
            </div>
          </section>
        </div>
     </div>
  </div>
</div>

app/views/homepage/perspectives.html.erb
<div class="container-fluid container-about-seeme">
  <h2 class="title text-center"><%= t('perspectives.title') %></h2>
  <div class="row sub-content">
    <div class="col-md-6">
      <div class="inner_sub-content">
        <h3><%= t('perspectives.presentation.title') %></h3>
        <p><%= t('perspectives.presentation.paragraph_one_html') %></p>
        <p><%= t('perspectives.presentation.paragraph_two_html') %></p>
        <p><%= t('perspectives.presentation.paragraph_three_html') %></p>
        <p><%= t('perspectives.presentation.paragraph_four_html') %></p>
      </div>
    </div>
    <div class="col-md-6">
      <h3><%= t('perspectives.besoin.title') %></h3>
        <ul><%= t('perspectives.besoin.list_html') %></ul>
    </div>
  </div>
  <div class="lines">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
</div>

app/views/homepage/press.html.erb
<div class="container container-press">
  <div class="hero-title">
    <div class="col-8">
      <h2><%=  t('press.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag "" %>
    </div>
  </div>
  <div class="content content-medias">
    <div class="media">
      <div class="media_header">
        <div class="media__title">
          <h4>
            <%= t('press.media-title') %> 
          </h4>
          <span><i class="far fa-calendar-alt"></i><%= t('press.date') %></span>
        </div>
        <%= link_to 'https://www.youtube.com/watch?fbclid=IwAR31YyKhWi6sOlivfpTB2TWx42335eqVlsFQwNzwYVr-xGb7LypgJVgvndc&v=l266h7RW6fc&feature=youtu.be', target: "_blank" do %>
          <%= image_tag("youtube-icon-logo.png", class: "little_img_press") %>
        <% end %>
      </div>
      <p class="description"><%= t('press.description') %></p>
    </div>

    <div class="media">
      <div class="media_header">
        <div class="media__title">
          <h4>
            <%= t('press.media-title-two') %> 
          </h4>
          <span><i class="far fa-calendar-alt"></i><%= t('press.date-two') %></span>
        </div>
        <%= link_to 'https://plus.lesoir.be/131564/article/2017-12-29/imane-cest-extraordinaire-de-pouvoir-offrir-un-bout-de-vie-normale', target: "_blank" do %>
          <%= image_tag("lesoir-logo.png", class: "little_img_press") %>
        <% end %>
      </div>
      <p class="description"><%= t('press.description-two') %></p>
    </div>

    <div class="media">
      <div class="media_header">
        <div class="media__title">
          <h4>
            <%= t('press.media-title-three') %> 
          </h4>
          <span><i class="far fa-calendar-alt"></i><%= t('press.date-three') %></span>
        </div>
        <%= link_to 'https://plus.lesoir.be/277978/article/2020-02-06/grand-format-lhistoire-dun-bebe-syrien-arrive-presque-tout-seul-en-belgique?referer=%2Farchives%2Frecherche%3Fdatefilter%3Dlastyear%26sort%3Ddate%2520desc%26word%3Db%25C3%25A9b%25C3%25A9%2520syrien', target: "_blank" do %>
          <%= image_tag("lesoir-logo.png", class: "little_img_press") %>
        <% end %>
      </div>
      <p class="description"><%= t('press.description-three') %></p>
    </div>

    <div class="media">
      <div class="media_header">
        <div class="media__title">
          <h4>
            <%= t('press.media-title-four') %> 
          </h4>
          <span><i class="far fa-calendar-alt"></i><%= t('press.date-four') %></span>
        </div>
        <%= link_to 'https://plus.lesoir.be/277978/article/2020-02-06/grand-format-lhistoire-dun-bebe-syrien-arrive-presque-tout-seul-en-belgique?referer=%2Farchives%2Frecherche%3Fdatefilter%3Dlastyear%26sort%3Ddate%2520desc%26word%3Db%25C3%25A9b%25C3%25A9%2520syrien', target: "_blank" do %>
          <%= image_tag("bruzz_logo.png", class: "little_img_press") %>
        <% end %>
      </div>
      <p class="description"><%= t('press.description-four') %></p>
    </div>


  </div>
</div>

app/views/homepage/private_life.html.erb
<div class="container container_private_life">
  <div class="row hero-title">
    <div class="col-8">
      <h2><%= t('private.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag("image_privacy-life.png") %>
    </div>
  </div>
  <h5><%= t('private.info_asbl') %></h5>
  <p><%= t('private.info_asbl_text_html') %></p>
  <p><%= t('private.introduction_html') %></p>
  <h5><%= t('private.subtitle_personnal_data') %></h5>
  <p><%= t('private.personnal_data_html') %></p>
  <h5><%= t('private.utilisation_data') %></h5>
  <p><%= t('private.personnal_data_text_html') %></p>
  <h5><%= t('private.legal_base') %></h5>
  <p><%= t('private.legal_base_text_html') %></p>
  <h5><%= t('private.delay_conservation') %></h5>
  <p><%= t('private.delay_conservation_text_html') %></p>
  <h5><%= t('private.cookies') %></h5>
  <p><%= t('private.cookies_text_html') %></p>
  <h5><%= t('private.your_rights') %></h5>
  <p><%= t('private.your_rights_text_html') %></p>
  <h5><%= t('private.contact_private_life') %></h5>
  <p><%= t('private.contact_private_life_text_html') %></p>
</div>

app/views/homepage/support.html.erb
<div class="container container-support">
  <div class="hero-title">
    <div class="col-8">
      <h2><%=  t('support.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag "support.png" %>
    </div>
  </div>
  <div class="content">
     <p class="description"><%= t('support.description') %></p>
     <div class="help_content">
        <div class="tab_container">
          <button class="btn link_tab_container" data-tab="1">
            <span><%= t('support.header.financial') %></span>
          </button>
          <button class="btn link_tab_container" data-tab="2" >
            <span><%= t('support.header.volonteer') %></span>
          </button>
        </div>
        <div class="bloc_section">
          <section class="section__content section__content1">
            <div class="description">
              <p><%= t('support.content.one_html') %></p>
            </div>
          </section>
          <section class="section__content section__content2">
            <div class="description">
              <p><%= t('support.content.two_html') %></p>
              <%= link_to t('support.content.form'), new_volunteer_path %>
            </div>
          </section>
        </div>
     </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer-seeme footer footer-light footer-shadow content container-fluid">
  <div class="container text-center text-md-left">
    <hr>
    <div class="row d-flex align-items-center">
      <div class="col-md-7 col-lg-8">
        <p class="text-center text-md-left">© 2020 See-Me | Developed by :
          <a href="https://www.qscar.be" target="_blank">Qscar Digital</a> | 
          <%= link_to t('footer.private-life'), private_life_path %>
        </p>
      </div>
      <div class="col-md-5 col-lg-4 ml-lg-0">
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a href="https://www.facebook.com/jumpforrefugees/" target="_blanck" class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://twitter.com/jumpforrefugees" target="_blank" class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "See Me", root_path , class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <span class="nav-link"><%=  t('header.about_us') %></span>
        <div class="dropdown-content">
          <%= link_to t('header.qui_sommes_nous'), about_path, class: "nav-link" %>
          <%= link_to t('header.history'), history_path, class: "nav-link" %>
          <%= link_to t('header.francois_house'), francois_house_path, class: "nav-link" %>
          <%= link_to t('header.perspectives'), perspectives_path, class: "nav-link" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to t('header.projets'), projects_path ,  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('header.agir'), new_volunteer_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <span class="nav-link"><%=  t('header.soutenir') %></span>
        <div class="dropdown-content">
          <%= link_to t('header.support'), support_path, class: "nav-link" %>
          <%= link_to t('header.partenaire'), partenaire_path, class: "nav-link" %>
        </div>
      </li>
      <li class="nav-item">
        
      </li>
      <li class="nav-item">
        <%= link_to t('header.presse'), press_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('header.contact'), contact_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('header.testimony'), testimony_path, class: "nav-link" %>
      </li>
    </ul>
    <!--<span class="">
      <ul class="langages-list">
        <li><%= link_to t('header.en'), locale: "en" %></li>
        <li><%= link_to t('header.fr'), locale: "fr" %></li>
        <li><%= link_to t('header.nl'), locale: "nl" %></li>
        <li><%= link_to t('header.ar'), locale: "ar" %></li>
      </ul>
    </span>-->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeeMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/index.html.erb
<div class="container_projects" data-turbolinks="false">
  <h2><%= t('project.index.title') %></h2>

  <div class="content">
    <div class="header_presentation">
      <ul>
        <% @projects.each do |project| %>
          <li>
            <div class="block_presentation">
              <a href="#project-<%= project.id %>">
                <%= image_tag project.image, class: "project_img" %>
                <div class="project_title"><h4><%= project.title %></h4></div>
              </a>
            </div>
          </li>
        <% end %>
        
      </ul>
    </div>
    <div class="lines">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
    <div class="more_informations_content">
      <% @projects.each do |project| %>
        <div class="inner_more_informations_content project" id="project-<%= project.id %>" > 
          <h3><%= project.title %></h3>
          <div class="bloc_description">
            <p><%= project.description %></p>
            <button class="button_seeme"><%= link_to t('project.index.inscription'), new_student_path %></button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container_trainees" data-turbolinks="false">
  <h2><%= t('trainees.new.title') %></h2>

  <div class="content">
    <div class="header_presentation">
      <%= form_with model: @trainee  do |f| %>
        <%= debug f.class %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </p>
        <p>
          <%= f.label :lastname %>
          <%= f.text_field :lastname %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </p>
        <p>
          <%= f.label :telephone %>
          <%= f.telephone_field :telephone %>
        </p>
        <div>
          <%= f.fields_for :projects do |project| %>
            <%= project.collection_radio_buttons :project_id, Project.all, :id, :title %>
          <% end %>
        </div>
        <%= f.submit "Submit" %>
      <% end %>
    </div>
    <div class="lines">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</div>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/new.html.erb
<div class="container container_student">
  <div class="hero-title">
    <div class="col-8 ">
      <h2><%= t('students.new.title') %></h2>
    </div>
    <div class="col-4">
      <%= image_tag("subscription.jpg") %>
    </div>
  </div>
  <p><%= t('students.new.description') %></p>
  <%= form_for @student, :html => {:class => "form_inscription"} do |f| %>
    <div class="block_name">
      <p>
        <%= f.text_field :name, class: "name", :placeholder => "#{t('students.new.name')}", class: "col-10" %>
        <i class="fas fa-asterisk"></i>
      </p>  
      <p>
        <%= f.text_field :lastname, :placeholder => "#{t('students.new.lastname')}", class: "col-10" %>
        <i class="fas fa-asterisk"></i>
      </p>
    </div>
    <p>
      <%= f.text_field :email, :placeholder => "#{t('students.new.email')}", class: "col-11" %>
      <i class="fas fa-asterisk"></i>
    </p>
    <p>
      <%= f.text_field :telephone, :placeholder => "#{t('students.new.phone')}", class: "col-11"  %>
      <i class="fas fa-asterisk"></i>
    </p>
    <div class="radio_buttons_block">
      <%= f.collection_radio_buttons :project_id, Project.all, :id, :title,  html: { class: "new_post" }, :class => 'input__field input__field-nile radio' %>
    </div>
    <%= f.submit t('students.new.submit_button'), class: "col-12 btn button_seeme"  %>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="container container_student">
  <div class="hero-title">
    <div class="col-8">
      <h2><%=  "#{t('students.show.title')}#{@student.name}" %></h2>
    </div>
    <div class="col-4">
      <%= image_tag("") %>
    </div>
  </div>
  <p><%= t('students.show.description') %></p>
  <p><%= t('students.show.description_two') %></p>
  <button class="button_seeme">
    <%= link_to t('cta.back_hompeage'), root_path %>
  </button>
</div>

app/views/trainees/show.html.erb
<h2><%= t('trainees.show.title') %></h2>

app/views/volunteers/create.html.erb
<h1>Volunteers#create</h1>
<p>Find me in app/views/volunteers/create.html.erb</p>